### ISSUE TITLE
setup.sh failing when trying to install plugin

### ISSUE THREAD

**Issue by ankitbansal82** [itsabot/abot#101]
I am setting up 'abot' on my windows box. setup shell script fails at the very last step of installing the plugins. error is mentioned below. I am using the default plugins.json file (with no dependencies). Can some one please suggest whats going wrong?

output from a bash shell.

bash-3.1$ cd /c/working/src/github.com/itsabot/abot/
bash-3.1$ cmd/setup.sh

* [starting] ***********************************************************

    [ok] checking for go binary
    [ok] checking GOPATH
    [ok] installing dependency manager
    [ok] syncing dependencies
    [ok] installing glock hook
    [ok] installing abot
    [ok] checking for psql binary
    [ok] checking postgres connection
    [ok] checking for abot database
    [ok] checking for abot_test database
  [warn] running abot migrations
         database migrations failed
         if the database has already been migrated, you can ignore this message
  [warn] running abot_test migrations
         database migrations failed
         if the database has already been migrated, you can ignore this message
    [ok] checking if abot database is seeded
    [ok] checking if abot_test database is seeded
   [err] installing abot plugins (this may take a minute)

   [cmd] abot plugin install

Fetching 0 plugins...

Failed to install plugins. exec: "/bin/sh": file does not exist
bash-3.1$

**Comment by St0ner1995** [comment]
What are you using to run it on Windows?

**Comment by ankitbansal82** [comment]
you mean the bash shell? I use a console emulator http://cmder.net/
I hope abot can run on windows machine? DO I need to use some sort of hosting wrapper?

**Comment by St0ner1995** [comment]
cmder does not have shell (sh). It has the Bourne again shell (bash). I think Cygwin has the shell interpreter

**Comment by St0ner1995** [comment]
The problem your having is your Linux environment does not have the shell prompt, that's all the error is

**Comment by ankitbansal82** [comment]
ok let me try cygwin.

**Comment by ankitbansal82** [comment]
So abot specifically requires shell instead of bash?

**Comment by St0ner1995** [comment]
The plugin install script does, yes

**Comment by ankitbansal82** [comment]
Before i try set this up, just wanted to check if abot can be setup on windows?

**Comment by St0ner1995** [comment]
Honestly, i have not tried it

**Comment by ankitbansal82** [comment]
I think you can remove the dependency on shell by changing abot.go

Change this 
 Command("/bin/sh", "-c", "go get ./...").
to 
Command("go","get","./...").

Its exactly the same outcome without dependency on the shell.

**Comment by lmaw** [comment]
Hey ankitbansal82, I have the exact same problem.. You should know that there are alot of bugs with Abot on Windows. Please let me know if you found a fix and how you did it, Thanks in adnvanced :) 

/Fred

**Comment by ankitbansal82** [comment]
i have managed to get past the setup.sh. Now onto abot server. Will let you know all steps I had to do to get it running. Once I am through.

**Comment by egtann** [comment]
Try deleting `plugins.go` and re-running `abot server`. This should be fixed in an upcoming patch.

**Comment by egtann** [comment]
Should be fixed by #105. Give it a shot and let me know!

**Comment by ankitbansal82** [comment]
It was due to a trailing comma when starting server with no plugins. I did went past it. But i keep hitting other nagging issues on windows platform. 
I am giving it a shot on ubuntu now, if it works for me then i can look to make the code compatible on windows.

**Comment by ankitbansal82** [comment]
Just for your reference, next issue i hit is in the compiledassets.sh.
On windows i havent managed to get the ln command working.
