### ISSUE TITLE
DB Error

### ISSUE THREAD

**Issue by arashahmadi** [itsabot/abot#104]
Hi there,

I have installed abot but when I run the console or on we page I get this error message : 

could not set memory at __state_entered to %!!(MISSING)s(bool=true). pq: syntax error at or near "ON

I use Postgres 9.5

Thank you
Arash

**Comment by egtann** [comment]
What's the output of the following?

`ps aux | grep -i postgres`

`which psql`

`psql --version`

Also, what operating system?

**Comment by arashahmadi** [comment]
ps aux | grep -i postgres
postgres    802  0.0  0.1 295220  1780 ?        S    17:49   0:00 /usr/lib/postgresql/9.4/bin/postgres -D /var/lib/postgresql/9.4/main -c config_file=/etc/postgresql/9.4/main/postgresql.conf
postgres    840  0.0  0.0 295220   240 ?        Ss   17:49   0:00 postgres: checkpointer process                                                                                              
postgres    841  0.0  0.0 295220   100 ?        Ss   17:49   0:00 postgres: writer process                                                                                                    
postgres    842  0.0  0.0 295220     0 ?        Ss   17:49   0:00 postgres: wal writer process                                                                                                
postgres    843  0.0  0.2 295620  2480 ?        Ss   17:49   0:00 postgres: autovacuum launcher process                                                                                       
postgres    844  0.0  0.1 150364  1316 ?        Ss   17:49   0:00 postgres: stats collector process                                                                                           
arash      4238  0.0  0.2  13696  2060 pts/4    S+   18:31   0:00 grep --color=auto -i postgres

which psql
/usr/bin/psql


psql (PostgreSQL) 9.5.2

OS : Ubuntu 15.04

Thank you

**Comment by egtann** [comment]
> postgres 802 0.0 0.1 295220 1780 ? S 17:49 0:00 /usr/lib/**postgresql/9.4**/bin/postgres -D

Postgres 9.4, right there. Remove all your versions of Postgres from your system then install Postgres 9.5. Take a look at our .travis.yml to see how to do that:

```
sudo apt-get -y remove --purge postgresql-9.4
sudo apt-get -y autoremove
sudo apt-key adv --keyserver keys.gnupg.net --recv-keys 7FCC7D46ACCC4CF8
sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
sudo apt-get update
sudo apt-get -y install postgresql-9.5
```
