### ISSUE TITLE
Making my plugin to get called by Abot

### ISSUE THREAD

**Issue by samuel-pt** [itsabot/abot#109]
This is a not an issue but clarification. 

I've installed the sample plugin plugin_hello. Installation is fine and I see this plugin is added plugin.go. 

And I've started abot using abot server and then connected to it using ```abot c +1310555344```. But when I issue a message I don't find my plugin got invoked. 

I tried sending messages like "say", "something", "hi"... But always I am getting the response which is constructed from github.com/itsabot/abot/core/nlp.go 

I also tried adding some Commands and Objects in github.com/itsabot/plugin_hello/hello.go and provided those in console, but of no use.

Am I missing something basic? Please let me  know how can I make abot to call my plugin?

**Comment by egtann** [comment]
Definitely a bug on my end. Just pushed a large update yesterday, and that must've broken this. I'll look into that this AM and get a fix out! Sorry about that.

**Comment by egtann** [comment]
Also should be fixed with #110.  Be sure to pull the latest changes from Abot, then also fetch the latest changes from plugin_hello.

**Comment by samuel-pt** [comment]
Now my plugin is called by abot
