### ISSUE TITLE
postgres driver initialisation in abot.go expects blank password for postgres user

### ISSUE THREAD

**Issue by ankitbansal82** [itsabot/abot#112]
If I set the password for the postgres user in PSQL and  then execute
cmd/setup.sh postgres:password@localhost

script fails at the point of initializing abot.go. I am sure password is correct because steps for checking postgres connection and checking abot database pass without any error.

`
* [starting] ***********************************************************

    [ok] checking for go binary
    [ok] checking GOPATH
    [ok] installing dependency manager
    [ok] syncing dependencies
    [ok] installing glock hook
    [ok] installing abot
    [ok] checking for psql binary
    [ok] checking postgres connection
    [ok] checking for abot database
    [ok] checking for abot_test database
  [warn] running abot migrations
         database migrations failed
         if the database has already been migrated, you can ignore this message
  [warn] running abot_test migrations
         database migrations failed
         if the database has already been migrated, you can ignore this message
    [ok] checking if abot database is seeded
    [ok] checking if abot_test database is seeded
   [err] installing abot plugins (this may take a minute)

   [cmd] abot plugin install

2016/05/14 21:09:06 pq: password authentication failed for user "postgres"
ankit@ubuntu:~/working/src/github.com/itsabot/abot$ 
`

The pg_hba.conf has auth_method set to "peer" for postgres user.

**Comment by egtann** [comment]
I believe you'll need to change peer to "md5" in your pg_hba.conf then restart Postgres to use a password option.

**Comment by ankitbansal82** [comment]
Tried two options - not sure where to go from here.
**Option 1: change auth_method to md5**
Same result as before

> ankit@ubuntu:~/working/src/github.com/itsabot/abot$ cmd/setup.sh postgres:Postgres1234@localhost
* [starting] ***********************************************************
    [ok] checking for go binary
    [ok] checking GOPATH
    [ok] installing dependency manager
    [ok] syncing dependencies
    [ok] installing glock hook
    [ok] installing abot
    [ok] checking for psql binary
    [ok] checking postgres connection
    [ok] checking for abot database
    [ok] checking for abot_test database
  [warn] running abot migrations
         database migrations failed
         if the database has already been migrated, you can ignore this message
  [warn] running abot_test migrations
         database migrations failed
         if the database has already been migrated, you can ignore this message
    [ok] checking if abot database is seeded
    [ok] checking if abot_test database is seeded
   [err] installing abot plugins (this may take a minute)
   [cmd] abot plugin install
2016/05/14 21:45:21 pq: password authentication failed for user "postgres"


**Option 2: Go back to blank password**
by logging to psql using 

> sudo -u postgres psql postgres
and then use \Password
to set blank password

But then script starts breaking at point of checking postgres connection

   ankit@ubuntu:~/working/src/github.com/itsabot/abot$cmd/setup.sh postgres@localhost
   [starting] ***********************************************************
  
  [ok] checking for go binary
    [ok] checking GOPATH
    [ok] installing dependency manager
    [ok] syncing dependencies
    [ok] installing glock hook
    [ok] installing abot
    [ok] checking for psql binary
   [err] checking postgres connection
         unable to connect to postgres
         please check your connection parameters...
         (host: localhost, port 5432, user: postgres, pass: )
         ... and make sure postgres is running
   [cmd] psql -w -h 'localhost' -p '5432' -U 'postgres' -v ON_ERROR_STOP=1 -c '\q'
psql: fe_sendauth: no password supplied

**Comment by egtann** [comment]
Try passing `127.0.0.1` instead of `localhost`

**Comment by ankitbansal82** [comment]
Didn't help. Same results as before.

Any clue why importing lib/pq is attempting to connect to postgres.

> _ "github.com/lib/pq" // Postgres driver

**Comment by ankitbansal82** [comment]
Found the root cause.

It's the call to create a new plugin from within the init function of weather plugin
p, err = plugin.New("github.com/itsabot/plugin_weather")

This New() method is trying to connectDB() but upto this point the main() func in abot.go has not been executed and env parameters for DB url are not set, and thus it fails.

So env variables need to be loaded before anyone else can connectDB.
