### ISSUE TITLE
Plugins in abot are note deployed in heroku

### ISSUE THREAD

**Issue by samuel-pt** [itsabot/abot#116]
I've added some sample plugins to my abot running in local. Now I want this whole setup to be deployed in heroku. I followed the steps present in https://github.com/itsabot/abot/wiki/Getting-Started#deploying-your-abot

Now my abot instance is running in heroku. But all my plugins are NOT deployed along with abot. I just see the default messages when I connect it abot running in heroku.

How can I deploy my plugins along with aBot in heroku?

**Comment by egtann** [comment]
Can you send me the repos of the plugins in question? I'll try to reproduce the problem

**Comment by samuel-pt** [comment]
I've just installed https://github.com/itsabot/plugin_weather and https://github.com/itsabot/plugin_hello in my aBot instance

**Comment by egtann** [comment]
Found the problem. Plugins.go had to be included in source control for Heroku, but it was in `.gitignore`. I've removed that file from .gitignore.

To fix this problem:
1. Pull the latest changes from Abot
2. Add and commit your `plugins.go` to git (if you don't have one, then run `abot p install`)
3. Re-push to Heroku and all should work!

Closing the issue now as it should be resolved. If you still have issues, let me know!

**Comment by samuel-pt** [comment]
Thanks for looking into this issue.

Now heroku is expecting the plugin packages to be present. Here is the error

remote: -----> Running: go install -tags heroku github.com/itsabot/abot
remote: plugins.go:5:2: cannot find package "github.com/itsabot/plugin_hello" in any of:
remote: 	/app/tmp/cache/go1.6/go/src/github.com/itsabot/plugin_hello (from $GOROOT)
remote: 	/app/go/src/github.com/itsabot/plugin_hello (from $GOPATH)
remote: plugins.go:6:2: cannot find package "github.com/itsabot/plugin_weather" in any of:
remote: 	/app/tmp/cache/go1.6/go/src/github.com/itsabot/plugin_weather (from $GOROOT)
remote: 	/app/go/src/github.com/itsabot/plugin_weather (from $GOPATH)
remote: 
remote:  !     Push rejected, failed to compile Go app
remote: 
remote: Verifying deploy...
remote: 
remote: !	Push rejected to abot-springml.
remote: 
To https://git.heroku.com/abot-springml.git
 ! [remote rejected] master -> master (pre-receive hook declined)

**Comment by egtann** [comment]
Heroku is an odd beast. I've changed the build script to fix that. Try
re-deploying to Heroku now.


E

**Comment by samuel-pt** [comment]
Redeploying solved the problem. Thanks a lot
