### ISSUE TITLE
Admin Dashboard

### ISSUE THREAD

**Issue by egtann** [itsabot/abot#118]
I'm building an admin dashboard to replace the old (and not very useful) getting started page. Here's a WIP screenshot.

Goals of mine are to:

- Help you stay up-to-date, ensuring you're running the latest Abot version
- Help you set up your Abot completely with all the new functionality that's being added (Account Connect, etc.), as well as surface that new functionality after each update
- Showcase the plugins you've installed and connect you to find more
- Show basic usage stats (with support later for graphs/visualizations)

I'd love any feedback. Right now it's just front-end work, so it's all still pretty flexible.

![Admin Dashboard](http://i.imgur.com/k7uNOkP.png)

**Comment by lmaw** [comment]
Looks Cool, Clean and simple! So I also made a Admin dashboard inspired by your design and I changed it a little bit. I had nothing to do on school so thats the main reason why I made this. but, I cant no scope/trickshot like a real designer. I hope you like it!
![testabot9](https://cloud.githubusercontent.com/assets/18270914/15405860/1d90d0b8-1e04-11e6-834e-b2e69f1f6245.png)

**Comment by mwthayer** [comment]
A few UX thoughts in no particular order

- Move plug-in dashboard to the left (in addition to or in replacement of its current position)
- Allow for data dumps (If currently allowed, add a dashboard button for it)
- Specify "Train your bot" (Avoids confusion with end-user training)

**Comment by egtann** [comment]
@lmaw looks cool. I like the footer in the bottom left.

@mwthayer 
- The dashboard is responsive, so sometimes it's in the left spot. Sometimes it isn't. These things move :)
- Data dump like exporting your current data to CSV? I could definitely add that.
- Will change, thanks!

**Comment by mwthayer** [comment]
1) It's fine if it moves but I think that as a major function, it should stay on the left as well.
2) Yes. Maybe give them a list of data points which would be the columns for them to select and then they can download.

**Comment by egtann** [comment]
#119 Merged with this. Closing
