### ISSUE TITLE
Multiple handles for the same response

### ISSUE THREAD

**Issue by Jamalish** [itsabot/abot#13]

**Comment by egtann** [comment]
Hi Cory.

To identify the issue, could you provide more details?  I'll need three pieces of information to solve this:

1. What did you do? Which endpoint did you hit?
2. What happened? What response was returned?
3. What were you expecting to happen? What's the desired behavior?

**Comment by Jamalish** [comment]
Hey,
Sorry about this, made the issue on the wrong repo.
