### ISSUE TITLE
use another language

### ISSUE THREAD

**Issue by goldalworming** [itsabot/abot#141]
hi, how do I implement in another languange. should I change all words and senteces in existing to my language?

**Comment by egtann** [comment]
You should build a plugin that registers to listen to incoming messages and translates them into English via some API. Save the original language choice with Memory if there's multiple possible languages you're answering. Then in that same plugin, register to listen to outgoing messages and translate them back into the original language.

You can find info about this in the Building a Plugin guide in the wiki (on Github).
