### ISSUE TITLE
Aiva

### ISSUE THREAD

**Issue by Ya-Ri** [itsabot/abot#142]
Hi,

i would like to inform you about another AI bot name AIVA(in the past : jarvis bot)
maybe you can work together, below you will find the developper home page:
https://github.com/kengz/aiva
http://kengz.me/aiva/

He works on AI bot since a long time. His experience can benefit to your project.
I have also posted a message on his github project page and hope you can collaborate for the benefit of the community.
i think we are many to wait for the integration with rocket.chat
Thank you for your works
Regards,
YaRi

**Comment by egtann** [comment]
Looks like a cool project. From what I can tell, AIVA's creator took the more classic approach (using Python NLP tools), whereas I've added additional layers of abstraction to try and make it easier for developers.

With our different approaches, architectures, and even programming languages, I'm not sure how to begin collaborating between the projects. Do you have some ideas on how we might combine our efforts?
