### ISSUE TITLE
Plugin installation fails

### ISSUE THREAD

**Issue by badgercl** [itsabot/abot#151]
Hi,

I'm following the Getting Started guide, but I couldn't  make it through the weather plugin example.

I configured the plugins.json file as follows:
```json
{
    "Dependencies": {
        "github.com/itsabot/plugin_weather": "*"
        }
}
```

and then I get an error when I run the install command:
```bash
$ abot plugin install
Fetching 1 plugin...
Installing plugins...
could not install plugins. failed to update itsabot.org.
Put /api/plugins.json: unsupported protocol scheme ""
```

I'm running Abot on a fresh go installation:
```bash
$ go version
go version go1.6 darwin/amd64
```

On a Mac running  OSX El Capitan 10.11.5.

Am I missing something?

Thanks for your help!

**Comment by egtann** [comment]
Good catch! Will fix.

For now, add this to your ~/.bashrc: `export ITSABOT_URL="https://www.itsabot.org"` to fix it.

**Comment by egtann** [comment]
In any event, #152 should fix this. Pull the latest changes, re-run and let me know!
