### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by inaiat** [itsabot/abot#16]
I tried to dockerize abot, but the postgres check on setup is by process(**ps ax -o comm | grep -q '^postgres')**. The postgres check should be a telnet on postgres port.

Step 15 : RUN ./cmd/setup.sh
 ---> Running in 63fd2e6a3688
    [ok] checking for go binary
    [ok] checking GOPATH
    [ok] installing dependency manager
    [ok] syncing dependencies
    [ok] installing glock hook
    [ok] installing abot
   [err] checking for postgres

failed cmd:
         ps ax -o comm | grep -q '^postgres'

**Comment by egtann** [comment]
Commands that follow also ensure that you're running on one machine, i.e. not containers. For instance the next check ensures that `psql` is in your `$PATH`.

I'd recommend making an option available to users when they run `cmd/setup.sh` that asks them if they're using containers `(Y/n)` and then runs different commands based on that response.

Could you put together a pull request for that?

**Comment by kaminskypavel** [comment]
@inaiat  were you able to work this around, if so please share the Dockerfile? we can try installing pgsql into the image before running setup.sh

**Comment by inaiat** [comment]
Ok. I will create a pull request!

Thanks in advanced

**Comment by egtann** [comment]
This is connected to issue #22. We're going to switch how we handle Postgres in development to match how we handle production, i.e. use a DATABASE_URL environment variable.  Hold off on any pull requests until we get that sorted out in the next few days.

**Comment by egtann** [comment]
#39 should provide a solution for you. You'll want to run `cmd/setup.sh` on your Abot container and `cmd/dbsetup.sh` inside your Postgres container.

Let me know how it goes!

**Comment by egtann** [comment]
In my testing, the split setup seems to work. I'm closing this issue. @inaiat @kaminskypavel if you're still having issues with Abot in Docker, we can discuss them here or in a new issue.

**Comment by DenisSergeevitch** [comment]
@inaiat hi, could you share a docker image for abot please?
