### ISSUE TITLE
error while installing `[err] syncing dependencies`

### ISSUE THREAD

**Issue by lordadamson** [itsabot/abot#17]
```
    [ok] checking for go binary
    [ok] checking GOPATH
    [ok] installing dependency manager
   [err] syncing dependencies

failed cmd:
         glock sync 'github.com/itsabot/abot'

bash: glock: command not found
```

**Comment by egtann** [comment]
Interesting.  It seems your $GOBIN isn't configured. Can you share the output of `echo $GOBIN`?

AFAIK a default installation of Go should point it toward /usr/local/go/bin

**Comment by lordadamson** [comment]
Hi, thanks for the reply.
I didn't have my GOBIN set. I did set it in my .bashrc. but before I did I installed glock manually using `go get github.com/robfig/glock` and now it works.
I don't know if the glock installation step was necessary or not. so I don't know if this is just a matter of $GOBIN or a missing dependency.
If there is anything I can do to help figure this out, please let me know. (I'm a noob in go so I wouldn't know on my own).

**Comment by lordadamson** [comment]
oh and by the way, it does work.

**Comment by egtann** [comment]
The glock installation step is handled automatically in cmd/setup.sh, but it looks like it was a GOBIN problem.  Go is a little tricky to install. Glad to hear it's sorted out!

**Comment by lordadamson** [comment]
Thank you! :)
