### ISSUE TITLE
Abot: Command Not Found

### ISSUE THREAD

**Issue by darrindickey** [itsabot/abot#174]
I've set up Go v.1.7, postgresql 9.5.4. I "go get github.com/itsabot/abot", which puts the abot exectuable in the /bin and github.com/itsabot/abot is downloaded to /src.

Run "abot new myNewproject" and I get -bash: abot: command not found. I've tried it in $GOPATH, $GOPATH/src, $GOPATH/src/github.com, $GOPATH/src/github.com/myuser, $GOPATH/src/github.com/itsabot. Doesn't seem to work anywhere.

Am I missing something?

**Comment by egtann** [comment]
Sounds like $GOPATH/bin isn't in your $PATH

**Comment by darrindickey** [comment]
That was it. Didn't realize I needed to add PATH to my bash_profile. Thanks.
