### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by DaleWebb** [itsabot/abot#21]
I'm interested in helping move this project forward, as I think it could be a significant part of my company's offering in the future.  I haven't used Go before, but I am a fast learner.

How can I help?

**Comment by egtann** [comment]
Hey Dale. It'd be great to have you on board.

If you're looking for tasks, I'd encourage you to check out our [How to Contribute](https://github.com/itsabot/abot/wiki/How-to-Contribute) guide, which has ideas for things to build. Right now the biggest impact changes are going to be building plugins that everyone can use. There are some ideas for plugins in the How to Contribute guide as well.

The [Getting Started](https://github.com/itsabot/abot/wiki/Getting-Started) and [Building a Plugin](https://github.com/itsabot/abot/wiki/Building-a-Plugin) guides should help you get up and running.

If you have any additional questions, we're happy to answer them over the [mailing list](https://groups.google.com/forum/#!topic/abot-discussion).

Best,

Evan

**Comment by DaleWebb** [comment]
Thanks!

I already had a look at the roadmap and the contribution guide, but I wanted to know if there was a priority on any of those (on the roadmap) and how to initialise work on one of those.

Sounds like plugins would be the best place to start, so I'll take a look at that.

I've just been accepted onto the mailing list :+1:

**Comment by egtann** [comment]
Great. Let me know if you have any additional questions! Happy to help.
