### ISSUE TITLE
 abot plugin install failing during install.

### ISSUE THREAD

**Issue by urupvog** [itsabot/abot#22]
I get this error during the setup

failed cmd:
         abot plugin install

When I just run abot plugin install on terminal, I get the following message:
2016/04/01 23:03:52 buildingpq: password authentication failed for user "postgres"

**Comment by egtann** [comment]
Have you created a Postgres user named "postgres"?  After that, did you run `cmd/setup.sh`?

**Comment by urupvog** [comment]
yes, I have a postgres user. \du on psql gives me this output:
                            List of roles
 Role name |                   Attributes                   | Member of 
-----------+------------------------------------------------+-----------
 postgres  | Superuser, Create role, Create DB, Replication | {}

**Comment by egtann** [comment]
And cmd/setup.sh ran successfully without any problems?

**Comment by urupvog** [comment]
Until the last step. here is the output. It asked postgres user a lot many times


cmd/setup.sh
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
    [ok] checking for go binary
    [ok] checking GOPATH
    [ok] installing dependency manager
    [ok] syncing dependencies
    [ok] installing glock hook
    [ok] installing abot
    [ok] checking for postgres
    [ok] checking for psql binary
     [?] checking for postgres userPassword for user postgres: 
    [ok] checking for postgres user
     [?] checking for abot databasePassword for user postgres: 
    [--] checking for abot database
         abot database missing. creating it
     [?] creating abot databasePassword: 
    [ok] creating abot database
     [?] checking for abot_test databasePassword for user postgres: 
    [--] checking for abot_test database
         abot_test database missing. creating it
     [?] creating abot_test databasePassword: 
    [ok] creating abot_test database
     [?] running abot migrationsPassword for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
    [ok] running abot migrations
     [?] running abot_test migrationsPassword for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
Password for user postgres: 
    [ok] running abot_test migrations
Password for user postgres: 
     [?] checking if abot database is seededPassword for user postgres: 
    [ok] checking if abot database is seeded
Password for user postgres: 
     [?] checking if abot_test database is seededPassword for user postgres: 
    [ok] checking if abot_test database is seeded
    [ok] generating environment file
   [err] installing abot plugins

failed cmd:
         abot plugin install

**Comment by egtann** [comment]
What does your pg_hba.conf look like?  Mine's at `/etc/postgresql/9.5/main/pg_hba.conf` but your location may be different.

The key line in the pg_hba.conf should look like this to enable password-less login:

```
local   all             postgres                                trust
```

or 

```
local   all             all                                     trust
```

**Comment by Jambo-Dunia** [comment]
This is mine:

#Database administrative login by Unix domain socket
`local   all             postgres                                md5
`
#TYPE  DATABASE        USER            ADDRESS                 METHOD

#"local" is for Unix domain socket connections only
`local   all             all                                     trust`
#IPv4 local connections:
`host    all             all             127.0.0.1/32            md5`
#IPv6 local connections:
`host    all             all             ::1/128                 md5
`

**Comment by egtann** [comment]
It's the `md5` after `local all postgres md5` that's causing the issues. We'll add support for password-based logins on the DB in development soon, but in the meantime you should be able to get it to work by changing

`local all postgres md5`

to

`local all postgres trust`

It's an interim solution, but a solution nonetheless. Let me know if that works for you!

**Comment by urupvog** [comment]
Mine was 
local all all md5. 

I changed that to
local all all trust.

and restarted the server.

Still the error.

**Comment by urupvog** [comment]
I commented other lines as well(Except local all all trust) and atleast it doesnt now ask me password 20 times. But the original problem still persists. I get an error failed cmd: abot plugin install during the setup. Putting the output below:


cmd/setup.sh
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
    [ok] checking for go binary
    [ok] checking GOPATH
    [ok] installing dependency manager
    [ok] syncing dependencies
    [ok] installing glock hook
    [ok] installing abot
    [ok] checking for postgres
    [ok] checking for psql binary
    [ok] checking for postgres user
    [ok] checking for abot database
    [ok] checking for abot_test database
  [warn] running abot migrations
database migrations failed
if the database has already been migrated, you can ignore this message

  [warn] running abot_test migrations
database migrations failed
if the database has already been migrated, you can ignore this message

    [ok] checking if abot database is seeded
    [ok] checking if abot_test database is seeded
    [ok] generating environment file
   [err] installing abot plugins

failed cmd:
         abot plugin install

**Comment by egtann** [comment]
Interesting. What happens when you run `abot plugin install` by itself?

We'll have a better fix for allowing password-based Postgres logins in development environments in the next few days.

**Comment by urupvog** [comment]
It gives me this error:
2016/04/02 00:18:50 buildingpq: no pg_hba.conf entry for host "::1", user "postgres", database "abot", SSL off

**Comment by Jambo-Dunia** [comment]
Changing to trust fixed my past error, Now im having troubles fetching plugins as well.

Fetching 1 plugins...
WARN: 500 - 500 Internal Server Error
Installing plugins...
/bin/sh: 1: glock: not found
exit status 127

**Comment by hernanc** [comment]
You can install Glock from: [https://github.com/robfig/glock](https://github.com/robfig/glock)

**Comment by egtann** [comment]
@Jambo-Dunia that's going to be a separate issue. It has to do with your $GOPATH/bin not being added to your $PATH. Make sure you've completed the Go install using these instructions here: https://golang.org/doc/install

**Comment by egtann** [comment]
@urupvog there appears to be an issue with your codebase from a modification. I would clone a clean version from GitHub and try again.

**Comment by urupvog** [comment]
Thanks. A clean clone resolved the issue.

**Comment by egtann** [comment]
Glad to hear it. Closing this issue.

For others referencing arriving on this thread, the solution was to modify pg_hba.conf from `local all postgres md5` to `local all postgres trust` as a temporary measure until we allow database use through a DATABASE_URL via an upcoming pull request.

**Comment by NassarX** [comment]
For windows users , `Local` refers to Unix sockets. Windows does not have them
So it maybe get you in trouble  , I used  `host    all             all             127.0.0.1/32            trust` and works
