### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by Dyldog** [itsabot/abot#27]
The server says: "failed http: named cookie not present", and the login page just resets.

I'm running the server on a Mac and I'm browsing through Safari.

**Comment by calliander** [comment]
This is happening for me but I don't yet know enough Golang to work it out. For the project authors, the AJAX call to authenticate isn't working. I don't know if it's the HAPIProfile or HAPIProfileView portion or something entirely different. Here's the AJAX error:

`main.js:2112 GET http://localhost:4200/api/user/profile.json 500 (Internal Server Error)`

In the DB, my account has a _locationid_ of 0, and a null _authorizationid_.

I'm still learning Go so I may figure this out.

**Comment by egtann** [comment]
Hey guys. Thanks for reporting the issue.

It's probably unrelated to locationid and authorizationid (which is only used for authorizing purchases over SMS). I'll dive into this and create a pull request to fix.

**Comment by egtann** [comment]
I'm unable to replicate the issue except by manually deleting cookies from my browser after sign-in. Tested on multiple browsers including Safari on a Mac.

Are you using any browser extensions which prevent cookies from being created or stored?

**Comment by calliander** [comment]
@egtann I made sure to use Chrome (49.0.2623.110 on 10.11.4) since it doesn't have anything installed to block cookies. However, I noticed my settings for content were a little more clamped down than default so I'm going to create another user on my machine so I can try with Chrome's default settings. I'll also check if it happens in other browsers with that user.

Server environment information is probably helpful, though.
- Centos 7.2.1511
- Golang 1.6 linux/amd64
- Postgres 9.5.2

@Dyldog What about your server/client environments?

**Comment by calliander** [comment]
@egtann No luck with the new user. After clearing all associated cookies, restarting the abot server, etc. I made sure I had none lingering then signed up. After signup I had 6:

- authToken (with a value)
- csrfToken (with a value)
- email (my urlencoded address)
- id (the corresponding user id from the db)
- issuedAt (the unix timestamp)
- scopes (empty value)

After pulling the latest changes it's still a 500 error, by the way.

**Comment by egtann** [comment]
> After pulling the latest changes it's still a 500 error, by the way.

Aha. The problem must be somewhere else in the handler. All those cookie values look good.

**Comment by Dyldog** [comment]
Tried Safari with no extensions, Chrome, and Firefox... No dice :(

Here's my env:
go version go1.6 darwin/amd64
postgres (PostgreSQL) 9.5.1
Abot version 0.2.0-alpha

**Comment by calliander** [comment]
@egtann It looks like it tries to set/get a cookie after signup, which the server reports the named cookie error on, along with any attempt to log in. And yeah, .../user/profile.json

I was going to fiddle with the JS so it prevents the form from submitting and see what it's erroring on after signup. I'll see what I can come up with.

**Comment by calliander** [comment]
@egtann JS can't read the secure cookies. On a regular flow Chrome reports secure as yes (but, httponly as no - I thought they were the same) and in the console, document.cookie is empty. If I set one manually, JS can read that cookie. Chrome reports the cookie as not secure.

**Comment by egtann** [comment]
I think I know the issue if it's a problem with secure cookies. Are you browsing Abot via some web address that doesn't include the string "localhost" in it?

If so, that's the issue, and I can have a fix out soon.

**Comment by calliander** [comment]
Yeah - even telling my hosts file that "localhost" is the IP of the VM doesn't work. Oddly, the cookies accurately reflect what the server is loaded on: Whether it's localhost or the IP. So strange!

Anyway, I look forward to the changes as they'll help in my quest to learn Go.

**Comment by egtann** [comment]
Just merged a fix: #41. Give it a shot now, and let me know if that fixes it for you!

**Comment by Dyldog** [comment]
Fixed, cheers!
