### ISSUE TITLE
Setup stuck on glock hook

### ISSUE THREAD

**Issue by chajas** [itsabot/abot#28]
I am installing abot on windows using cygwin. The setup is stuck on installing glock hook for past 30 mins. I tried it twice and network also seems to be fine.
Any suggestions? 
Including the output below.

```
 cmd/setup.sh
    [ok] checking for go binary
    [ok] checking GOPATH
    [ok] installing dependency manager
    [ok] syncing dependencies
     [?] installing glock hook
```

**Comment by egtann** [comment]
Hi @chajas. I haven't tested any of this outside of Linux/OSX, so I can't really comment. I would try running the command manually and check the output:

`glock install github.com/itsabot/abot --verbose`

Let us know what you find.

**Comment by RYOHOI** [comment]
![screen shot 2016-04-03 at 11 32 18 pm](https://cloud.githubusercontent.com/assets/5955526/14233218/fd36493e-f9f4-11e5-87d2-c690a25fff70.png)
![screen shot 2016-04-03 at 11 32 38 pm](https://cloud.githubusercontent.com/assets/5955526/14233219/fd86b022-f9f4-11e5-9844-77c1719ffa75.png)

I removed these 2 lines, and still getting error.

**Comment by egtann** [comment]
Without Glock managing dependencies you'll need to pull in the dependencies via Go manually:

`$ go get ./...`

Let me know how it goes.

**Comment by chajas** [comment]
For me 
$ glock install github.com/itsabot/abot --verbose

gets stuck endlessly as well.
However, when I remove the glock installation from the cmd/setup.sh it proceeds further but gets stuck at the below error.

I have postgres installed and running on my system. The postgres user is also present. I have also adjusted the server configuration to trust.

Not sure why this occurs. Any idea why ps ax -o would not be known?

```
$ cmd/setup.sh
    [ok] checking for go binary
    [ok] checking GOPATH
    [ok] installing dependency manager
    [ok] syncing dependencies
    [ok] installing abot
     [?] checking for postgresps: unknown option -- o
Try `ps --help' for more information.
   [err] checking for postgres

failed cmd:
         ps ax -o comm | grep -q '^postgres'

please start postgres to continue

```

**Comment by egtann** [comment]
@chajas are you on Windows?

**Comment by chajas** [comment]
yes trying to install abot on windows

**Comment by egtann** [comment]
I'd recommend running Abot on Linux or OSX.

Windows support is "nice-to-have" for us (I'll accept pull requests) but for now will probably be pretty buggy.

**Comment by RYOHOI** [comment]
Alright, I uncomment those two lines and get glock. It says command not found. I think I have difficulty installing glock.

![screen shot 2016-04-04 at 2 45 33 pm](https://cloud.githubusercontent.com/assets/5955526/14240028/07cf48a8-fa74-11e5-8a31-b11193791ce2.png)

**Comment by lipsumar** [comment]
@RYOHOI you're not the only one https://github.com/robfig/glock/issues/32
I have the same issue. I'm on Mac OSX 10.9.5 and just installed Go.
I believe the Go users know what to do... Anyone ?

**Comment by egtann** [comment]
I'm closing this issue. We can discuss #32 in that thread.

**Comment by RYOHOI** [comment]
Still waiting for solution……

**Comment by egtann** [comment]
This issue is closed. If you'd like help, please find it in robfig/glock#32.
