### ISSUE TITLE
err while checking for postgres

### ISSUE THREAD

**Issue by NassarX** [itsabot/abot#36]
$ cmd/setup.sh
    [ok] checking for go binary
    [ok] checking GOPATH
    [ok] installing dependency manager
    [ok] syncing dependencies
    [ok] installing glock hook
    [ok] installing abot
     [?] checking for postgresps: unknown option -- o
Try `ps --help' for more information.
   [err] checking for postgres

failed cmd:
         ps ax -o comm | grep -q '^postgres'

please start postgres to continue

**Comment by aburgd** [comment]
Have you tried to start postgres? And what platform are you on?

**Comment by NassarX** [comment]
@aburgd  yes postgresql service is running , on windows 10

**Comment by egtann** [comment]
Looks like you don't have a Linux/BSD compatible `ps`. Try removing the trouble line from setup.sh and re-running.

**Comment by NassarX** [comment]
@egtann now it's holding here [?] checking for postgres user

**Comment by egtann** [comment]
Try the latest `cmd/setup.sh` from #39 to see if anything's changed. You can now pass in your specific Postgres details as a command line arg while running that. See the README for the added functionality.

**Comment by NassarX** [comment]
ok it's work now but that's the new next error
```
Fetching 1 plugins...
exec: "/bin/sh": file does not exist

```

**Comment by Jambo-Dunia** [comment]
@NassarX you have to go through the source and replace "/bin/sh" with "sh" if you are on windows I believe.

**Comment by egtann** [comment]
For now, I'd recommend running Abot on Linux or OSX. While it may work on Windows, you may continue to experience weird bugs. It's much easier to boot up a VM.

I'll be adding a Linux/OSX requirement to the README and closing Windows-related issues, marking them as wont-fix. That said I am open to accepting PRs for Windows fixes as long as it doesn't impact the other platforms.
