### ISSUE TITLE
Unable to connect to Abot on any port

### ISSUE THREAD

**Issue by aburgd** [itsabot/abot#37]
I have the abot server running - at least so it says - but whenever I go into Chrome to connect, it refuses to connect. I have tried different ports, changing the port in various places (ie `abot.env`, `.zshrc`, and made an `env` named `PORT`), all to no avail. I used the `abot c[onsole]` command, and whenever I try to interact with it, I get:

```
$ abot server
2016/04/02 22:50:43 started Abot
2016/04/02 22:51:43 failed to queue scheduled event missing destination name id
2016/04/02 22:51:46 failed to process text missing user
```

I have Abot running in a Trusty 64-bit Vagrant box, PostgreSQL 9.5.2, and Go 1.6, if that helps any.

**Comment by egtann** [comment]
Just to be clear, you're exposing any ports out of Vagrant you'll need, right? You should be able to connect on localhost:4200.

You'll have to create a user to send Abot messages in the console--that's the error you're seeing.

**Comment by aburgd** [comment]
The thought hadn't even crossed my mind - with other stuff I've used, like the gotour, it just worked out of the gate. I guess I'll have to go back and look.

**Comment by aburgd** [comment]
Alright, after opening the ports and reloading my box it worked! Thanks for the reminder.
