### ISSUE TITLE
`abot plugin install` fails: GLOCKFILE not found

### ISSUE THREAD

**Issue by exetwezz** [itsabot/abot#40]
I'm getting an error while running `abot plugin install`, whether manually or through `cmd/setup.sh`:

```
$ abot plugin install
Fetching 1 plugins...
WARN: 500 - 500 Internal Server Error
Installing plugins...
error creating %!!(MISSING)s(func(string) string=0x410d00): open /home/yuri/projects/src/home/yuri/projects/src/github.com/itsabot/abot/GLOCKFILE: no such file or directory

exit status 1
```
```
$ cmd/setup.sh
    [ok] checking for go binary
    [ok] checking GOPATH
    [ok] installing dependency manager
    [ok] syncing dependencies
    [ok] installing glock hook
    [ok] installing abot
    [ok] checking for postgres
    [ok] checking for psql binary
    [ok] checking for postgres user
    [ok] checking for abot database
    [ok] checking for abot_test database
  [warn] running abot migrations
database migrations failed
if the database has already been migrated, you can ignore this message

  [warn] running abot_test migrations
database migrations failed
if the database has already been migrated, you can ignore this message

    [ok] checking if abot database is seeded
    [ok] checking if abot_test database is seeded
    [ok] generating environment file
   [err] installing abot plugins

failed cmd:
         abot plugin install

Fetching 1 plugins...
WARN: 500 - 500 Internal Server Error
Installing plugins...
error creating %!!(MISSING)s(func(string) string=0x410d00): open /home/yuri/projects/src/home/yuri/projects/src/github.com/itsabot/abot/GLOCKFILE: no such file or directory

exit status 1
```
As you can see, the problem is that GLOCKFILE couldn't be found, because it's supposed to be at location which is constructed incorrectly: `/home/yuri/projects/src/home/yuri/projects/src/github.com/itsabot/abot/GLOCKFILE` should be `/home/yuri/projects/src/github.com/itsabot/abot/GLOCKFILE`, which exists.

Notice that `$GOPATH/src` (`/home/yuri/projects/src`) is added to the glockfile location - is it possible to remove it? Thanks

**Comment by egtann** [comment]
From within your abot directory, what does `pwd | sed "s|$GOPATH/src/||"` output?

**Comment by damtsnkff** [comment]
I'm facing the exact same issue. 
Also, here is my outputs : 
For `echo $GOPATH` it returns :  `/Users/#NAME#/abotest/`
and for `pwd | sed "s|$GOPATH/src/||"` : `/Users/#NAME#/abotest/src/github.com/itsabot/abot`

**Comment by damtsnkff** [comment]
@exetwezz  Found out!
I ran `echo $PATH`, and it returned me something like `:/Users/damientsenkoff/abotest//bin:`
I just removed `/` at the end of `export GOPATH=/Users/damientsenkoff/abotest` inside my `.bash_profile`.

**Comment by egtann** [comment]
Great to hear. Closing this issue. @exetwezz if you're still experiencing problems after implementing the fix above, let me know here.
