### ISSUE TITLE
Database errors

### ISSUE THREAD

**Issue by duncanleo** [itsabot/abot#42]
Hi, when attempting to set abot up and running in a vagrant instance (Ubuntu 14.04) (with Go 1.6 and Postgres 9.5) it falls apart at database migrations. At the very start during sign-up, it says that the `userflexids` table is missing. After manually creating the table (from the first file in db/migrations) it goes on to a 'syntax error near 'ON'' error.

**Comment by egtann** [comment]
You'll need Postgres 9.5+

**Comment by duncanleo** [comment]
I think that a previous Postgres installation may have borked things, trying it out on another Ubuntu instance worked. Thanks! :+1:
