### ISSUE TITLE
Communicate with HTTP or WS?

### ISSUE THREAD

**Issue by swennemans** [itsabot/abot#43]
Currently I'm trying to build my own bot. However, following the guide it seems that you can either communicate with the the console or SMS but the website states there an HTTP API is exposed. 

So is there a way to communicatie with the bot using HTTP/WS? Any pointers (example or code) how I could utilize this?

Thanks :)

**Comment by swennemans** [comment]
Found it. I will added my answer for reference. 

I found the test in the weather plugin. Unfortunately building his test fails, but the URL needed seems to be indicated here: 

```
	req := "what's the weather in LA?"
	u := fmt.Sprintf("http://localhost:%s?flexidtype=2&flexid=%s&cmd=%s",
		os.Getenv("PORT"), url.QueryEscape(phone), url.QueryEscape(req))
```

Then: 

`curl -H "Content-Type: application/json" -d '{"flexidtype":2,"flexid":"+13105555555", "cmd" : "hi"}' http://localhost:4200/`


Isn't this something that should be in the documentation? Or is it left out on purpose? :)

**Comment by egtann** [comment]
You can see how we communicate over HTTP via the Abot console command (inside abot.go). The console is a much nicer interface for testing over HTTP. You're right though, curl instructions should be added to the guides. I'll reopen this issue and plan to add those shortly.

**Comment by egtann** [comment]
Added `curl` and custom endpoint instructions for `abot console` to the Getting Started guide. https://github.com/itsabot/abot/wiki/Getting-Started#communicating-with-abot
