### ISSUE TITLE
Deploying to Heroku Issues

### ISSUE THREAD

**Issue by shalomabitan** [itsabot/abot#49]
Hi,

Super stoked to try abot. I've followed the guide closely and tried it multiple times in case I was mistaken, but each time I get the following error message when trying to deploy for the first time to heroku

```
remote: -----> Syncing plugin dependencies...
remote: /tmp/buildpack20160406-164-1x6e9x4/bin/compile: line 339: cd: /app/go/src/github.com/itsabot/abot/plugins: No such file or directory
remote: 
remote:  !     Push rejected, failed to compile Go app
```

any suggestions?

thanks

**Comment by egtann** [comment]
Ah, we've changed how we handle plugins, but apparently not in the Heroku Buildpack. I'll get a fix out shortly.

**Comment by egtann** [comment]
Issue should be fixed with https://github.com/itsabot/heroku-buildpack-go/commit/2ba44f7cac112059ed35479f2a754c9275944254. If there are any other problems, feel free to open a new issue.

Thanks!

Evan
