### ISSUE TITLE
Wireframe iteration of lightly styled Abot front end.  

### ISSUE THREAD

**Issue by mikeumus** [itsabot/abot#51]
As per [Roadmap v0.2.0 Front-end: 2](https://github.com/itsabot/abot/wiki/Roadmap#v020---shipping-june-1-2016)

An initial wireframe iteration of the Abot Server home page:
- https://abot.mybalsamiq.com/projects/abotui/Abot%20Server%20Index

![Abot Server home page Balsamiq wireframe](https://899b9e6dc933a1148ee10041c39d7571174d1695.googledrive.com/host/0B9LVk4xbDIJTaWExbjNNVFI3anc)

**Comment by egtann** [comment]
Cool!  I like this grid idea!  Interested in exploring this further

**Comment by egtann** [comment]
Hey @mikeumus, any updates on this? Any way I can help?

**Comment by mikeumus** [comment]
Pardon just been busy with freelancing trying to get things out and make rent. Have a customer who doesn't want to pay even half their bill. Times are a little hard right now.

**Comment by egtann** [comment]
Sorry to hear that!  Ok, just checking in. Best of luck!

**Comment by egtann** [comment]
FYI, Mike I'm starting to do a bunch of work on the interface now via #68. I'd hold off on any changes for the moment
