### ISSUE TITLE
What IA algorithms use Abot?

### ISSUE THREAD

**Issue by cristianchaparroa** [itsabot/abot#54]
I would like to know what IA algorithms is based Abot?

**Comment by njaremko** [comment]
The only type of algorithms that I know by "IA Algorithms" are immune
algorithms...and to the best of my knowledge Abot doesn't use them. Almost
nobody uses them.

**Comment by egtann** [comment]
I'm assuming he means AI algorithms, but since this isn't an issue with Abot, please move discussion to the Mailing List. You can find a link to the mailing list in the README. Closing
