### ISSUE TITLE
How do I handle asking for information only when needed?

### ISSUE THREAD

**Issue by eviltoylet** [itsabot/abot#56]
The current implementation of the state machine requires that `StateMachine.Next()` be called twice. Once so that the code in `OnEntry()` is run and then on the subsequent call, `OnInput()` and `OnComplete()`. I noticed that there is a `SkipIfComplete`, but using it seems wrong.

For example, I want to support the following homogeneously:
- What's the weather in Seattle?
    - bot: The weather is 55 degrees and cloudy.
- What's the weather?
    - bot: What city do you want the weather for?
    - me: Seattle
    - bot: The weather is 55 degrees and cloudy.

What I'm inclined to do is just to use `SkipIfComplete` and do all the logic within `Complete()`. What's the approach that you would suggest?

**Comment by njaremko** [comment]
Have you read the wiki? (https://github.com/itsabot/abot/wiki/Building-a-Plugin)

SkipIfComplete and dt,Memory should allow you to only ask the city once. You can set your triggers so that if the user asks for a specific city you return the weather for that new city and remember.

**Comment by egtann** [comment]
Yup, the correct answer is to store the city in memory using `dt.SetMemory`, which is what the state machine would do internally, but could also be done from within a keyword handler.

**Comment by eviltoylet** [comment]
If there isn't a city in memory yet, where should the logic to extract out the city and store it live? I want it to live in a `State`, but there doesn't seem to be an easy way to do it. 

I understand that there are some structures built around city specifically, but for now, let's pretend there isn't. My problem domain isn't with cities, I just chose it because I thought it'd facilitate an easier discussion.

**Comment by njaremko** [comment]
You should be asking your question to the user OnEntry. Doing your parsing, work, and memorizing in OnInput. Then checking if it's stored in memory, and returning the value in Complete.

If you have SkipIfComplete set to true, it will jump to Complete at the beginning, but if Complete returns false it goes through the state normally.

**Comment by eviltoylet** [comment]
I want to be able to have the option to not ask a question `OnEntry()` in the case that the user has provided all the necessary data. How do I do that? I think if you tried to implement it, you'll run into the same issue.

Say I'm running a plugin for purchasing items. I have states that gathers information about the item, the brand, the quantity, and when to buy it. I can:
- ask all the information in a piece meal fashion through all the steps (i.e. buy ketchup)
- or, not ask if all that information is provided. (i.e. Buy two gallons of Heinz ketchup tomorrow)

**Comment by egtann** [comment]
I'd say build a keyword handler for the case where the user provides all information (in this example triggering on "Buy" and "ketchup." If all the necessary information is parsed and saved to memory in that function, you could return a response, e.g. "Ok, it's on its way." But you'll want to check the length of the response from the keyword handler to determine if it's necessary to enter your state machine (no response -> there's still unfinished steps). Once in the state machine, if the SkipIfCompletes are set up correctly (and that bug fixed ;)) it should jump right to the appropriate next question, e.g. per this example:

"Buy Heinz ketchup tomorrow."  -> "How much should I buy?"  ->  "2 gallons"
"Buy two gallons of ketchup"  ->  "When should I buy it?"

**Comment by eviltoylet** [comment]
The implementation in `state_machine.go` is a linear workflow engine and it isn't as flexible as a true state machine. There are also still some bugs in the current implementation.

I would recommend the following modifications:
- Remove `onEntry`, `onInput`, and `Complete` and replace with one method called `process(in *dt.Msg, iteration int) int`. `iteration` indicates the number of iterations we've been in this state. The initial iteration is 0.
- `process` will return an integer to indicate the next state to transition to. If no transition can happen, then the integer of the current state would be returned. There should be a special value like `-1` for the terminal state.
- A channel should be provided which can be used to solicit further input from the user.

**Comment by njaremko** [comment]
- I'm okay with this, but not sure we should replace the current `state_machine`...maybe rename the current implementation to `workflow.go,` and implement the new FSM as `state_machine.go`? Maybe by the time the `state_machine` is complete the old `workflow` will seem redundant and we can depreciate it, but for now I think its a useful abstraction for new programmers writing a plugin.

- I'm okay with us re-implementing `state_machine` to be a true FSM, but I think we should stick to labels for indicating which state to transition to. Remembering integers in a large state machine will get tedious.

- Not sure a channel is necessary for additional communication. Assuming each complete state prints to the user, you should be able to handle this in the state machine.

**Comment by egtann** [comment]
@eviltoylet I'm not sure I agree. A state machine by definition must ensure that its states are both "mutually exclusive" and "all inclusive," meaning that given a set of inputs, there can only be one logical state to run, and all combinations of inputs must result in entering a state. The state machine in its current design (discounting bugs) fulfills that definition. It's also domain specific, but that doesn't disqualify it as a finite state machine.

**Comment by eviltoylet** [comment]
@egtann you're correct. What is currently there is indeed a state machine, it just doesn't have as much flexibility as I would like. The domain which it addresses is extremely narrow and it won't work for any cases beyond the following:

- prompt user for information (`onEntry`)
- process the provided information (`onInput`)
- if the right information was given, go to the next state (`Complete`)

I would like to keep processing of information in `onInput` instead of performing it external to the state machine. Currently, if `SkipIfComplete` is set `OnInput` isn't called prior to `Complete.` I don't know if such a change would cause issues with existing plugins. (`https://github.com/eviltoylet/abot/commit/c5a7a9b3f5608461a57b8450657a7f4981cc7dd7`)

Here are some of the things that I find myself implementing that I wish were provided:
- keeping track of all `Msg`s that have been provided so they can be referenced from other states. It'll make for more natural conversations.
    - you: Show me movie times for Star Wars, tonight
    - me: For which theater?
    - you: AMC in Seattle
    - me: For what time?
    - you: ...
You've already given the temporal reference of tonight earlier, but I don't have that information at this point.

Does this make sense?

**Comment by egtann** [comment]
The design goal is specifically to *avoid* having to reference prior messages, as that greatly complicates plugin development. From experience, we should do everything in our power to avoid having to do that! :)

I believe what you've implemented above can be done entirely within the current state machine design, and the end result should be pretty easy to reason about.

What about this structure?

States:

1. Get movie name. OnInput also parses and saves using some shared functions with the states below, e.g. ExtractTime, ExtractTheater
2. Get theater, skipifcomplete HasMemory "favorite_theater"
3. Get time, skipifcomplete HasMemory "time"

OnReset DeleteMemory "time" 

If you want to allow overriding the theater, set a keyword handler to trigger on theater names, e.g. AMC and ensure those are in the data/nouns file. Soon we'll have the training interface, so that step won't be necessary, but in the interim that should work.

Let me know!

**Comment by eviltoylet** [comment]
I've jumped into the IRC channel. It'll be faster to talk through the issue there and then post back to this thread with a summary.

**Comment by egtann** [comment]
@eviltoylet is this issue solved? From our discussion in IRC, I believe you can use a combination of a KeywordHandler (to parse everything and save it into memory) with a State Machine (like the one described above) to handle this case.

**Comment by egtann** [comment]
@eviltoylet Just to follow up, I've been thinking a lot about this and plugin API. I think you're right, and we can dramatically simplify the API. Basically Reset() and keyword handling -> state machine could be automated, and we don't lose any flexibility if we do that. You also shouldn't have to build a state machine--that can be handled for you.

So expect some changes in the next few weeks to the plugin API that should make things much easier!

**Comment by eviltoylet** [comment]
:thumbsup:

**Comment by egtann** [comment]
@eviltoylet here's a new look at the plugin API I'm thinking about. It's not implemented in Abot itself yet, but it will be soon.  https://github.com/egtann/plugin_weather/blob/master/weather.go

You can see that as a plugin developer you won't have to call `Run` or `FollowUp`, build a state machine, or check if `len(resp) == 0` or manage state machine resets. In the vast majority of cases you just set VocabHandlers and States. Everything else is handled for you automatically.

This change gives us a very nice perk for v0.3 as well. Since VocabHandlers and States are nice little independent logic blocks and all the logic of plugins outside of that has been extracted to Abot's core, we can pretty easily build a visual plugin editor. Ideally you shouldn't need to code to build plugins (although that will always be an option)--you should be able to drag and drop pre-made/tested blocks, like a "getCity" block which would extract a city to be passed onto the next block.

Anyway, just wanted to update you on this front!
