### ISSUE TITLE
HasMemory is broken

### ISSUE THREAD

**Issue by eviltoylet** [itsabot/abot#58]
`StateMachine.HasMemory()` doesn't work as advertised. It's doing a check on a length of the byte buffer, which is not empty for a JSON marshaled string. It needs to be marshaled to a string before this check is done.

**Comment by njaremko** [comment]
Has memory works as intended...it queries the DB and returns the JSON response if there are no errors. If there's an error (it doesn't exist in the DB), then it sets Val = json.RawMessage{} which is an empty []byte.

**Comment by eviltoylet** [comment]
There's a disconnect here then. In the example here: `https://github.com/itsabot/abot/wiki/Building-a-Plugin`, `SetMemory()` is called with an empty string which is not going to result in the DB not having that row. There needs to be a way to remove a value.

**Comment by njaremko** [comment]
*Disclaimer I haven't actually used the Memory datatype*
An empty string is nil when marshaling, so it's unmarshaled as an empty []byte. However, if someone stores a customer marshaled struct, then it probably will break...

The entry in the db is overwritten if a new value is passed to `SetMemory()`

**Comment by egtann** [comment]
All the following are equal to zero, though, so it seems HasMemory's implementation will work. Is there some reason you need to delete the row?

```go
fmt.Println(len([]byte{}))
fmt.Println(len(""))
fmt.Println(len("") == len([]byte{}))
```

**Comment by eviltoylet** [comment]
```
package main

import (
	"fmt"
	"encoding/json"
)

func main() {
	b,_ := json.Marshal("")
	fmt.Println(b)
}
```

```
[34 34]
```

**Comment by egtann** [comment]
Great catch. Will accept a pull request.

**Comment by njaremko** [comment]
To fix this issue, should probably also include a check for an empty string in `HasMemory()`

**Comment by egtann** [comment]
If we were to do that solution, we should also check for "null" (as a string) in case memory was set to nil. It gets a little messy, and people shouldn't be setting memory to "" or nil anymore.  I think we should just allow the breaking change and encourage people to delete memories (as this PR does).

E




On Tue, Apr 12, 2016 at 7:09 AM -0700, "Nathan Jaremko" <notifications@github.com<mailto:notifications@github.com>> wrote:


To fix this issue, should probably also include a check for an empty string in HasMemory()

-

**Comment by njaremko** [comment]
We can force devs to implement an IsEmpty interface on a struct they make. Then when we retrieve from the DB and unmarshal we can just call the IsEmpty method.

**Comment by egtann** [comment]
That's much more complex than just using DeleteMemory, which is what they should be doing
