### ISSUE TITLE
Messages should not be limited to 255 chars

### ISSUE THREAD

**Issue by eviltoylet** [itsabot/abot#67]
This is because the underlying column has type `character varying(255)`.

**Comment by egtann** [comment]
Yes, we should switch this to TEXT

**Comment by sharang-d** [comment]
Hey guys, is the column in question named 'sentence' in the 'messages' table?

**Comment by egtann** [comment]
Yup! We'd need a new pair of up/down migrations to modify that column.

To get the timestamp like the other migrations have, try `$ date +%s`

**Comment by sharang-d** [comment]
Are you creating the migrations by hand or is there some package/library helping you with it? Another follow up question: as a general rule/guideline what command/s do I run to check if I haven't broken anything(tests!)? I can't find that in the contributing guide or elsewhere. Thanks in advance. 😄

**Comment by sharang-d** [comment]
I tried `go test` but I get 
```
2016/04/21 22:14:48 failed to start server could not connect to database: dial tcp 127.0.0.1:5432: getsockopt: connection refused
```
Probably something wrong with my Db..

**Comment by egtann** [comment]
Yes, that's an error in trying to connect to your DB. Did you run `cmd/setup.sh`? Did it skip DB setup or run through everything there? Do you have Postgres running?

There's no tool to make migrations. Just create the files and write the SQL--should be one line.

**Comment by sharang-d** [comment]
Is this output normal?
```
➜  abot git:(master) go test ./...
ok  	github.com/itsabot/abot	7.197s
ok  	github.com/itsabot/abot/core	0.177s
?   	github.com/itsabot/abot/core/log	[no test files]
?   	github.com/itsabot/abot/core/template	[no test files]
?   	github.com/itsabot/abot/core/websocket	[no test files]
?   	github.com/itsabot/abot/data/ner	[no test files]
?   	github.com/itsabot/abot/shared/datatypes	[no test files]
?   	github.com/itsabot/abot/shared/helpers/address	[no test files]
?   	github.com/itsabot/abot/shared/helpers/timeparse	[no test files]
?   	github.com/itsabot/abot/shared/interface/cal	[no test files]
?   	github.com/itsabot/abot/shared/interface/cal/driver	[no test files]
?   	github.com/itsabot/abot/shared/interface/email	[no test files]
?   	github.com/itsabot/abot/shared/interface/email/driver	[no test files]
?   	github.com/itsabot/abot/shared/interface/emailsender	[no test files]
?   	github.com/itsabot/abot/shared/interface/emailsender/driver	[no test files]
?   	github.com/itsabot/abot/shared/interface/payment	[no test files]
?   	github.com/itsabot/abot/shared/interface/payment/driver	[no test files]
?   	github.com/itsabot/abot/shared/interface/sms	[no test files]
?   	github.com/itsabot/abot/shared/interface/sms/driver	[no test files]
?   	github.com/itsabot/abot/shared/knowledge	[no test files]
ok  	github.com/itsabot/abot/shared/language	0.047s
?   	github.com/itsabot/abot/shared/nlp	[no test files]
?   	github.com/itsabot/abot/shared/plugin	[no test files]
?   	github.com/itsabot/abot/shared/task	[no test files]
```

Sorry I deleted my earlier post before you replied.. my db wasn't running. 😛

**Comment by egtann** [comment]
Yup, that means it all passed! When you create a pull request TravisCI will automatically run all the tests as well.

**Comment by sharang-d** [comment]
Thanks, I'll get to work and send in some code soon hopefully!
