### ISSUE TITLE
Training Interface Mockup

### ISSUE THREAD

**Issue by egtann** [itsabot/abot#68]
![Training Interface Mockup](http://i.imgur.com/7RZmMg7.png)

Here's my thinking for the first version of the training interface, which will enable you to train your Abot:

- Plugins should be trained individually. That is, I train the `alarm` and `restaurants` plugins separately.
- Training data of published plugins must be shared to enable those plugins to work. I'm thinking of supporting two models simultaneously:
    1. Encode training data into a text file and save it with the plugin (open-source trained model)
    1. Make it available via an external HTTP request (closed-source trained model). This will enable developers to charge money or protect particularly complex trained models.
- The Intent mentioned here would be available to plugins via StructuredInput.
- Over time we can expand this design with:
    - In-line testing, so you can quickly iterate without jumping back to the console, perhaps via a keyboard shortcut.
    - The ability to add additional, custom fields beyond Intent.
    - Auto-completion on the field (set_alarm, disable_alarm, etc.) with past values.
    - Display real user requests to that plugin, with requests that the plugin couldn't handle sorted to the top.

Would love feedback!

**Comment by martyhimself** [comment]
This looks great! A first question I have would be, what does it train? Does it effectively create the command-object combinations creators of plugins would usually have to supply 'manually' ? In the third example in your picture, does it 'train' the plug in to recognise 'turn off' as effectively an alias for 'disable', within the context of this plug in? _Training_ seems to suggest that when an algorithm is presented with _new _data, it is somehow able to infer meaning or suggest a solution- that doesn't seem to be happening here? (sorry I may be completely wrong here- hope I'm not diluting the dicussion).

**Comment by njaremko** [comment]
I think it's training input -> function called because in most cases people are going to use "the" plugin for each task they want to accomplish, so the popular plugins will amass a large body of training input. At least for the open source part anyway....for the closed source complex machine learning mega awesome trained models, I assume they'll be able to parse input and check command-object combinations for similar intent/synonyms.

**Comment by egtann** [comment]
> Training seems to suggest that when an algorithm is presented with new data, it is somehow able to infer meaning or suggest a solution

@martyhimself That's exactly what this does. You teach it the types of sentences that relate to intents, then it can infer (on sentences it hasn't yet seen) what the intent should be. The intent is an alternative trigger to Command/Object.  That is, I could say, on intent set_alarm run my alarm plugin, then run the setAlarm function.

**Comment by itsbalamurali** [comment]
[double_intent.pdf](https://github.com/itsabot/abot/files/226411/double_intent.pdf)

**Comment by egtann** [comment]
Very interesting linked article on double intent. This design actually lays the groundwork to support that.  A sentence can have one intent from one plugin and a separate intent from another plugin. We don't currently have a way to route to two plugins at once and manage the conversation across both of them simultaneously, but I _can_ imagine adding support for that in v.3 (ETA August 1st, 2016) at the same time that we start supporting multiple independent commands per incoming user request (e.g. set my alarm to 5pm and remind me to pick up groceries then).

**Comment by egtann** [comment]
![Admin Panel](http://i.imgur.com/REWaCCI.png)

First pics of my work on the new admin panel/training interface. Starting to come together!

I'm having to take a different approach in storing training data than described above. It'll now all be available via a central service, defaulting to itsabot.org for simplicity in getting started (it should "just work," but you could self-host too). This change will allow you to deploy on Heroku and any sort of clustered deployment where you need to share the same info--synced--across multiple instances.

**Comment by egtann** [comment]
Changes are now merged! There's a new admin interface, which includes working training functionality around intent.
