### ISSUE TITLE
Something went wrong with my wiring - Error

### ISSUE THREAD

**Issue by samuel-pt** [itsabot/abot#74]
I've just starting to use abot. 
I followed https://github.com/itsabot/abot/wiki/Getting-Started guide and able to use abot console.

I've installed the two plugins as mentioned [here](https://github.com/itsabot/abot/wiki/Getting-Started#installing-plugins)

Now when I connect via abot console and then issuing the text "What's the weather like in LA?" throws me an error 
`Something went wrong with my wiring... I'll get that fixed up soon.`

Did I miss anything?

**Comment by samuel-pt** [comment]
I got this message in "abot server" console

```
>:~/work/go_workspace/src/github.com/itsabot/abot (master)$ abot server
2016/04/21 18:00:30 started Abot
2016/04/21 18:00:40 failed to process text pq: column "flexid" of relation "messages" does not exist
2016/04/21 18:00:40 failed to process text pq: column "flexid" of relation "messages" does not exist

```

**Comment by egtann** [comment]
You'll need to run cmd/migrateup.sh. Ignore any errors, then retry.

**Comment by samuel-pt** [comment]
I don't see cmd/migrateup.sh. Do you mean dbsetup.sh or setup.sh?

**Comment by egtann** [comment]
Yes, try running cmd/setup.sh

**Comment by egtann** [comment]
@samuel-pt has this been fixed?

**Comment by samuel-pt** [comment]
No, not yet I facing some other issues. Today I will do a new clone and check this out.

**Comment by egtann** [comment]
@samuel-pt I'm going to close this issue for now. If you run into additional problems with the new install, just open a new issue.
