### ISSUE TITLE
Install 'go get github.com/itsabot/abot' results in "abot.go:234: syntax error: Unexpected range,'

### ISSUE THREAD

**Issue by danprime** [itsabot/abot#95]
Hi All,

I was following the installation instructions by doing `go get github.com/itsabot/abot` 

I got the following error messages:
[cmd] go install 'github.com/itsabot/abot'

 # github.com/itsabot/abot
./abot.go:234: syntax error: unexpected range, expecting {
./abot.go:237: syntax error: argument to go/defer must be function call
./abot.go:247: non-declaration statement outside function body
./abot.go:248: non-declaration statement outside function body
./abot.go:251: non-declaration statement outside function body
./abot.go:252: non-declaration statement outside function body
./abot.go:253: non-declaration statement outside function body
./abot.go:256: non-declaration statement outside function body
./abot.go:259: non-declaration statement outside function body
./abot.go:260: non-declaration statement outside function body
./abot.go:260: too many errors

> System Details
> go version go1.2.1 linux/amd64
> psql (PostgreSQL) 9.3.12
> 
> Operating System Details:
> Distributor ID:	LinuxMint
> Description:	Linux Mint 17.2 Rafaela
> Release:	17.2
> Codename:	rafaela
> 

Can anyone help me with these errors?

**Comment by egtann** [comment]
It's probably due to outdated dependencies. You need Go 1.6+ and Postgres 9.5+. If that doesn't fix it, let me know!
